In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import joblib
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [4]:
df = pd.read_csv('Dataset250V9.csv')
df

,Unnamed: 0,Status Hidup Ayah,Status Hidup Ibu,Status Kerja Ayah,Status Kerja Ibu,Tempat Tinggal,Penghasilan Orang Tua,Kartu PKH,KPS,KKS,Dinding Rumah,Lantai Rumah,Kondisi Rumah,Jumlah Tanggungan,Prestasi,Keaktifan Belajar,Pelanggaran di Sekolah,Penerima
0,1,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0
1,2,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0
2,3,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,3.0,1.0,0.0
3,4,0.0,1.0,0.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,3.0,1.0,0.0
4,5,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,246,1.0,0.0,1.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0,3.0,4.0,0.0,1.0
246,247,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,2.0,2.0,4.0,0.0,1.0
247,248,1.0,0.0,1.0,1.0,0.0,3.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,3.0,0.0,1.0
248,249,0.0,1.0,1.0,1.0,1.0,3.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0,2.0,3.0,0.0,1.0
249,250,0.0,0.0,1.0,1.0,0.0,3.0,0.0,1.0,1.0,1.0,1.0,0.0,2.0,2.0,3.0,1.0,1.0

In [3]:
print("data shape : ", df.shape)

data shape :  (250, 18)

In [20]:
df['Pelanggaran di Sekolah'].unique()

array([0., 1.])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              250 non-null    int64
 1   Status Hidup Ayah       250 non-null    float64
 2   Status Hidup Ibu        250 non-null    float64
 3   Status Kerja Ayah       250 non-null    float64
 4   Status Kerja Ibu        250 non-null    float64
 5   Tempat Tinggal          250 non-null    float64
 6   Penghasilan Orang Tua   250 non-null    float64
 7   Kartu PKH               250 non-null    float64
 8   KPS                     250 non-null    float64
 9   KKS                     250 non-null    float64
 10  Dinding Rumah           250 non-null    float64
 11  Lantai Rumah            250 non-null    float64
 12  Kondisi Rumah           250 non-null    float64
 13  Jumlah Tanggungan       250 non-null    float64
 14  Prestasi                250 non-null    float64
 15  Keaktifan Belajar       250 non-null    float64
 16  Pelanggaran di Sekolah  250 non-null    float64
 17  Penerima                250 non-null    float64
dtypes: float64(17), int64(1)
memory usage: 35.3 KB

In [8]:
df = df.drop(columns=['Unnamed: 0'], axis=1)

In [9]:
df[['Penghasilan Orang Tua', 'Prestasi', 'Keaktifan Belajar']].describe()

       Penghasilan Orang Tua    Prestasi  Keaktifan Belajar
count             250.000000  250.000000         250.000000
mean                2.300000    1.144000           3.148000
std                 1.216519    1.110042           0.669244
min                 0.000000    0.000000           1.000000
25%                 1.000000    0.000000           3.000000
50%                 2.000000    1.000000           3.000000
75%                 3.000000    2.000000           4.000000
max                 4.000000    3.000000           4.000000

In [10]:
df.Penerima.value_counts()

Penerima
0.0    125
1.0    125
Name: count, dtype: int64

In [11]:
df.duplicated().sum()

10

In [15]:
df = df.drop_duplicates()
df.duplicated().sum()

0

In [12]:
df.isnull().sum()

Status Hidup Ayah         0
Status Hidup Ibu          0
Status Kerja Ayah         0
Status Kerja Ibu          0
Tempat Tinggal            0
Penghasilan Orang Tua     0
Kartu PKH                 0
KPS                       0
KKS                       0
Dinding Rumah             0
Lantai Rumah              0
Kondisi Rumah             0
Jumlah Tanggungan         0
Prestasi                  0
Keaktifan Belajar         0
Pelanggaran di Sekolah    0
Penerima                  0
dtype: int64

In [16]:
df.corr()

,Status Hidup Ayah,Status Hidup Ibu,Status Kerja Ayah,Status Kerja Ibu,Tempat Tinggal,Penghasilan Orang Tua,Kartu PKH,KPS,KKS,Dinding Rumah,Lantai Rumah,Kondisi Rumah,Jumlah Tanggungan,Prestasi,Keaktifan Belajar,Pelanggaran di Sekolah,Penerima
Status Hidup Ayah,1.000000,0.076988,0.024098,-0.123304,0.050908,0.203854,0.058231,0.101021,0.093818,-0.002352,0.061083,0.117193,0.057463,0.295127,0.144751,-0.034251,0.266838
Status Hidup Ibu,0.076988,1.000000,-0.151196,-0.146828,-0.042168,0.240971,0.000515,0.057904,0.018762,0.065603,0.062890,0.056732,0.041677,0.205584,0.100891,-0.148428,0.217147
Status Kerja Ayah,0.024098,-0.151196,1.000000,0.184310,-0.008545,-0.199983,-0.005940,0.070093,0.008874,-0.167394,-0.060511,-0.002037,0.076774,-0.145767,-0.150499,-0.049747,-0.174406
Status Kerja Ibu,-0.123304,-0.146828,0.184310,1.000000,-0.055139,-0.403966,-0.193229,-0.017883,-0.085276,-0.221225,-0.083087,-0.143231,-0.026918,-0.452576,-0.236034,0.127579,-0.508881
Tempat Tinggal,0.050908,-0.042168,-0.008545,-0.055139,1.000000,0.172349,0.175019,0.118530,0.081509,0.054849,0.034905,0.062892,0.012220,0.151024,0.085218,0.049945,0.192573
Penghasilan Orang Tua,0.203854,0.240971,-0.199983,-0.403966,0.172349,1.000000,0.320693,0.108002,0.283022,0.205232,0.123623,0.112552,0.180681,0.654005,0.328838,-0.114314,0.796408
Kartu PKH,0.058231,0.000515,-0.005940,-0.193229,0.175019,0.320693,1.000000,0.109101,0.100305,0.118341,0.150905,0.039493,0.072496,0.356290,0.161274,-0.028009,0.461859
KPS,0.101021,0.057904,0.070093,-0.017883,0.118530,0.108002,0.109101,1.000000,0.058810,0.052636,0.071333,0.024564,-0.039189,0.124377,0.000945,0.038912,0.135043
KKS,0.093818,0.018762,0.008874,-0.085276,0.081509,0.283022,0.100305,0.058810,1.000000,0.087608,-0.017760,0.037824,0.023774,0.221317,0.136451,-0.110704,0.307825
Dinding Rumah,-0.002352,0.065603,-0.167394,-0.221225,0.054849,0.205232,0.118341,0.052636,0.087608,1.000000,-0.020028,-0.008018,0.089465,0.287665,0.138387,-0.150190,0.334913
Lantai Rumah,0.061083,0.062890,-0.060511,-0.083087,0.034905,0.123623,0.150905,0.071333,-0.017760,-0.020028,1.000000,0.102223,0.025360,0.224930,-0.029355,-0.003049,0.204044
Kondisi Rumah,0.117193,0.056732,-0.002037,-0.143231,0.062892,0.112552,0.039493,0.024564,0.037824,-0.008018,0.102223,1.000000,-0.056765,0.187853,0.151468,0.010615,0.193116
Jumlah Tanggungan,0.057463,0.041677,0.076774,-0.026918,0.012220,0.180681,0.072496,-0.039189,0.023774,0.089465,0.025360,-0.056765,1.000000,0.075916,-0.002183,-0.100376,0.178088
Prestasi,0.295127,0.205584,-0.145767,-0.452576,0.151024,0.654005,0.356290,0.124377,0.221317,0.287665,0.224930,0.187853,0.075916,1.000000,0.344701,-0.241062,0.815311
Keaktifan Belajar,0.144751,0.100891,-0.150499,-0.236034,0.085218,0.328838,0.161274,0.000945,0.136451,0.138387,-0.029355,0.151468,-0.002183,0.344701,1.000000,-0.101470,0.417571
Pelanggaran di Sekolah,-0.034251,-0.148428,-0.049747,0.127579,0.049945,-0.114314,-0.028009,0.038912,-0.110704,-0.150190,-0.003049,0.010615,-0.100376,-0.241062,-0.101470,1.000000,-0.242627
Penerima,0.266838,0.217147,-0.174406,-0.508881,0.192573,0.796408,0.461859,0.135043,0.307825,0.334913,0.204044,0.193116,0.178088,0.815311,0.417571,-0.242627,1.000000

In [23]:
df = df.drop(columns=['Unnamed: 0'])
df

,Status Hidup Ayah,Status Hidup Ibu,Status Kerja Ayah,Status Kerja Ibu,Tempat Tinggal,Penghasilan Orang Tua,Kartu PKH,KPS,KKS,Dinding Rumah,Lantai Rumah,Kondisi Rumah,Jumlah Tanggungan,Prestasi,Keaktifan Belajar,Pelanggaran di Sekolah,Penerima
0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0
1,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,3.0,1.0,0.0
3,0.0,1.0,0.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,3.0,1.0,0.0
4,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,1.0,0.0,1.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0,3.0,4.0,0.0,1.0
246,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,2.0,2.0,4.0,0.0,1.0
247,1.0,0.0,1.0,1.0,0.0,3.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,3.0,0.0,1.0
248,0.0,1.0,1.0,1.0,1.0,3.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0,2.0,3.0,0.0,1.0
249,0.0,0.0,1.0,1.0,0.0,3.0,0.0,1.0,1.0,1.0,1.0,0.0,2.0,2.0,3.0,1.0,1.0

In [26]:
x = df.drop(columns=['Penerima'])
y = df['Penerima']

print("x : ", x.shape)
print("y : ", y.shape)

x :  (250, 16)
y :  (250,)

In [28]:
x

,Status Hidup Ayah,Status Hidup Ibu,Status Kerja Ayah,Status Kerja Ibu,Tempat Tinggal,Penghasilan Orang Tua,Kartu PKH,KPS,KKS,Dinding Rumah,Lantai Rumah,Kondisi Rumah,Jumlah Tanggungan,Prestasi,Keaktifan Belajar,Pelanggaran di Sekolah
0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
1,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
2,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,3.0,1.0
3,0.0,1.0,0.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,3.0,1.0
4,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,1.0,0.0,1.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0,3.0,4.0,0.0
246,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,2.0,2.0,4.0,0.0
247,1.0,0.0,1.0,1.0,0.0,3.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,3.0,0.0
248,0.0,1.0,1.0,1.0,1.0,3.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0,2.0,3.0,0.0
249,0.0,0.0,1.0,1.0,0.0,3.0,0.0,1.0,1.0,1.0,1.0,0.0,2.0,2.0,3.0,1.0

In [18]:
scaler = StandardScaler()
scaler.fit(x)
x = scaler.transform(x)

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=42)

In [20]:
clf = SVC(kernel='linear')
clf.fit(x_train, y_train)

y_pred = clf.predict(x_test)
CLF_acc = accuracy_score(y_test, y_pred)

print(classification_report(y_test, y_pred))
print("Akurasi Model : {:.2f}%".format(CLF_acc * 100))

              precision    recall  f1-score   support

         0.0       0.96      0.96      0.96        24
         1.0       0.96      0.96      0.96        24

    accuracy                           0.96        48
   macro avg       0.96      0.96      0.96        48
weighted avg       0.96      0.96      0.96        48

Akurasi Model : 95.83%

In [28]:
joblib.dump(clf, 'svm_model.pkl')
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']

In [30]:
x

,Status Hidup Ayah,Status Hidup Ibu,Status Kerja Ayah,Status Kerja Ibu,Tempat Tinggal,Penghasilan Orang Tua,Kartu PKH,KPS,KKS,Dinding Rumah,Lantai Rumah,Kondisi Rumah,Jumlah Tanggungan,Prestasi,Keaktifan Belajar,Pelanggaran di Sekolah
0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
1,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
2,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,3.0,1.0
3,0.0,1.0,0.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,3.0,1.0
4,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,1.0,0.0,1.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0,3.0,4.0,0.0
246,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,2.0,2.0,4.0,0.0
247,1.0,0.0,1.0,1.0,0.0,3.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,3.0,0.0
248,0.0,1.0,1.0,1.0,1.0,3.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0,2.0,3.0,0.0
249,0.0,0.0,1.0,1.0,0.0,3.0,0.0,1.0,1.0,1.0,1.0,0.0,2.0,2.0,3.0,1.0

In [5]:
df['Kondisi Rumah'].unique()

array([0., 1.])

In [31]:
output = ""
for column in df.columns:
    unique_values = df[column].unique()
    output += f"Kolom: {column}\n"
    output += f"Nilai unik: {unique_values}\n\n"

# Menampilkan semua data
print(output)

Kolom: Status Hidup Ayah
Nilai unik: [0. 1.]

Kolom: Status Hidup Ibu
Nilai unik: [0. 1.]

Kolom: Status Kerja Ayah
Nilai unik: [1. 0.]

Kolom: Status Kerja Ibu
Nilai unik: [0. 1.]

Kolom: Tempat Tinggal
Nilai unik: [0. 1. 2.]

Kolom: Penghasilan Orang Tua
Nilai unik: [1. 2. 3. 0. 4.]

Kolom: Kartu PKH
Nilai unik: [1. 0.]

Kolom: KPS
Nilai unik: [0. 1.]

Kolom: KKS
Nilai unik: [0. 1.]

Kolom: Dinding Rumah
Nilai unik: [0. 1.]

Kolom: Lantai Rumah
Nilai unik: [0. 1.]

Kolom: Kondisi Rumah
Nilai unik: [0. 1.]

Kolom: Jumlah Tanggungan
Nilai unik: [0. 2. 1. 3. 4.]

Kolom: Prestasi
Nilai unik: [0. 1. 3. 2.]

Kolom: Keaktifan Belajar
Nilai unik: [3. 2. 4. 1.]

Kolom: Pelanggaran di Sekolah
Nilai unik: [0. 1.]

Kolom: Penerima
Nilai unik: [0. 1.]